# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

target "youtube-player-ios-example" do
  pod "youtube-ios-player-helper", :path => "../../youtube-ios-player-helper.podspec"

  target "youtube-player-ios-exampleTests" do
    pod "OCMock", "3.7.1"
  end
end
